[build-system]
requires = ["hatchling", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[project]
name = "boilerplate-micropython"
dynamic = ["version", "readme"]
description = "MicroPython driver for the Boilerplate"
license = {file = "LICENSE.txt"}
requires-python = ">= 3.9"
authors = [
    { name = "Philip Howard", email = "phil@pimoroni.com" },
]
maintainers = [
    { name = "Philip Howard", email = "phil@pimoroni.com" },
]
keywords = [
    "MicroPython",
    "Pico",
    "Pimoroni",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: Implementation :: MicroPython",
    "Topic :: Software Development :: Libraries",
    "Topic :: System :: Hardware :: Hardware Drivers",
]
dependencies = []

[project.urls]
GitHub = "https://www.github.com/pimoroni/boilerplate-micropython"
Homepage = "https://www.pimoroni.com"

[dependency-groups]
dev = [
    "check-manifest",
    "codespell",
    "coverage",
    "hatch",
    "hatch-fancy-pypi-readme",
    "pre-commit",
    "pytest",
    "ruff==0.16.5",
    "tox",
    "twine",
]

[tool.hatch.version]
path = "src/boilerplate.py"

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [
  { path = "README.md" },
  { text = "\n" },
  { path = "CHANGELOG.md" }
]

[tool.hatch.build]
include = [
    "src",
    "README.md",
    "CHANGELOG.md",
    "LICENSE.txt"
]

[tool.hatch.build.targets.wheel]
sources = ["src"]
include = [
    "src"
]

[tool.hatch.build.targets.sdist]
include = [
    "*"
]
exclude = [
    ".*",
    "dist",
    "uv.lock"
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
src = ["src", "."]
exclude = [
    '.tox',
    '.egg',
    '.git',
    '__pycache__',
    'build',
    'dist'
]
line-length = 200

[tool.ruff.lint]
extend-select = ["I", "UP", "SIM", "PIE", "C4", "B", "RUF", "PERF", "FURB", "PLE"]

[tool.codespell]
skip = """
./.tox,\
./.venv,\
./.egg,\
./.git,\
./__pycache__,\
./build,\
./dist\
"""

[tool.check-manifest]
ignore = [
    'Makefile',
    'tox.ini',
    'tests/*',
    'examples/*',
    'tools/*',
    'package.json',
    '.editorconfig',
    '.pre-commit-config.yaml'
]
